# Generated by Django 4.1.5 on 2023-01-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("yearofexp", models.FloatField()),
                ("education", models.CharField(max_length=300)),
                ("keyskills", models.CharField(max_length=500)),
                ("detailedskills", models.TextField()),
                ("interviewscore", models.CharField(max_length=4)),
                ("prefferedworklocation", models.CharField(max_length=500)),
                ("currentsalary", models.FloatField()),
                ("expectedsalary", models.FloatField()),
                ("doj", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[("Available", "Available"), ("Engaged", "Engaged")],
                        default="Available",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rid", models.CharField(max_length=5)),
                ("companyname", models.CharField(max_length=30)),
                ("jobarea", models.CharField(max_length=30)),
                ("resourcerequired", models.FloatField()),
                ("jd", models.TextField()),
                ("resourceremaining", models.FloatField()),
                (
                    "r_status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Open", "Closed")],
                        default="open",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "resources",
            },
        ),
    ]
