# Generated by Django 4.1.5 on 2023-01-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("L1interviewername", models.CharField(max_length=100)),
                ("L2interviewername", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Open", "Closed")],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "onboarding",
                    models.CharField(
                        choices=[("YES", "YES"), ("NO", "NO")],
                        default="YES",
                        max_length=20,
                    ),
                ),
                (
                    "hrid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Firstapp.recruiter",
                    ),
                ),
            ],
            options={
                "db_table": "hr",
            },
        ),
    ]
