# Generated by Django 4.1.5 on 2023-01-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Firstapp", "0002_hr"),
    ]

    operations = [
        migrations.AddField(
            model_name="hr",
            name="L1interviewdatetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="hr",
            name="L2interviewdatetime",
            field=models.DateTimeField(null=True),
        ),
    ]
